apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ..\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 80
  selector:
    io.kompose.service: ui
status:
  loadBalancer: {}
