/*
 * RapidGuestRegistration - OpenAPI 3.0
 *
 * This is the RapidGuestRegistration API, used for everything from creating tables to managing users, as well as registering for guests.
 *
 * The version of the OpenAPI document: 3.0.2
 * Contact: group-b@rapidguestregistration.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RapidGuestRegistration.Client.Api;
using RapidGuestRegistration.Client.Model;
using RapidGuestRegistration.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RapidGuestRegistration.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Booking
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BookingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Booking
        //private Booking instance;

        public BookingTests()
        {
            // TODO uncomment below to create an instance of Booking
            //instance = new Booking();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Booking
        /// </summary>
        [Fact]
        public void BookingInstanceTest()
        {
            // TODO uncomment below to test "IsType" Booking
            //Assert.IsType<Booking>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'LocationBooking'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'LocationBooking'
        }
        /// <summary>
        /// Test the property 'TableBooking'
        /// </summary>
        [Fact]
        public void TableTest()
        {
            // TODO unit test for the property 'TableBooking'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'People'
        /// </summary>
        [Fact]
        public void PeopleTest()
        {
            // TODO unit test for the property 'People'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

    }

}
