/*
 * RapidGuestRegistration - OpenAPI 3.0
 *
 * This is the RapidGuestRegistration API, used for everything from creating tables to managing users, as well as registering for guests.
 *
 * The version of the OpenAPI document: 3.0.2
 * Contact: group-b@rapidguestregistration.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RapidGuestRegistration.Client.Api;
using RapidGuestRegistration.Client.Model;
using RapidGuestRegistration.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RapidGuestRegistration.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Guest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GuestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Guest
        //private Guest instance;

        public GuestTests()
        {
            // TODO uncomment below to create an instance of Guest
            //instance = new Guest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Guest
        /// </summary>
        [Fact]
        public void GuestInstanceTest()
        {
            // TODO uncomment below to test "IsType" Guest
            //Assert.IsType<Guest>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }

    }

}
