/*
 * RapidGuestRegistration - OpenAPI 3.0
 *
 * This is the RapidGuestRegistration API, used for everything from creating tables to managing users, as well as registering for guests.
 *
 * The version of the OpenAPI document: 3.0.2
 * Contact: group-b@rapidguestregistration.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RapidGuestRegistration.Client.Api;
using RapidGuestRegistration.Client.Model;
using RapidGuestRegistration.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RapidGuestRegistration.Client.Test.Model
{
    /// <summary>
    ///  Class for testing InlineResponse2001
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2001Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2001
        //private InlineResponse2001 instance;

        public InlineResponse2001Tests()
        {
            // TODO uncomment below to create an instance of InlineResponse2001
            //instance = new InlineResponse2001();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse2001
        /// </summary>
        [Fact]
        public void InlineResponse2001InstanceTest()
        {
            // TODO uncomment below to test "IsType" InlineResponse2001
            //Assert.IsType<InlineResponse2001>(instance);
        }


        /// <summary>
        /// Test the property 'LocationId'
        /// </summary>
        [Fact]
        public void LocationIdTest()
        {
            // TODO unit test for the property 'LocationId'
        }
        /// <summary>
        /// Test the property 'TableId'
        /// </summary>
        [Fact]
        public void TableIdTest()
        {
            // TODO unit test for the property 'TableId'
        }
        /// <summary>
        /// Test the property 'DatetimeFrom'
        /// </summary>
        [Fact]
        public void DatetimeFromTest()
        {
            // TODO unit test for the property 'DatetimeFrom'
        }
        /// <summary>
        /// Test the property 'DatetimeTo'
        /// </summary>
        [Fact]
        public void DatetimeToTest()
        {
            // TODO unit test for the property 'DatetimeTo'
        }
        /// <summary>
        /// Test the property 'Report'
        /// </summary>
        [Fact]
        public void ReportTest()
        {
            // TODO unit test for the property 'Report'
        }

    }

}
