/*
 * RapidGuestRegistration - OpenAPI 3.0
 *
 * This is the RapidGuestRegistration API, used for everything from creating tables to managing users, as well as registering for guests.
 *
 * The version of the OpenAPI document: 3.0.2
 * Contact: group-b@rapidguestregistration.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RapidGuestRegistration.Client.Api;
using RapidGuestRegistration.Client.Model;
using RapidGuestRegistration.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RapidGuestRegistration.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Location
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LocationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Location
        //private Location instance;
        private Location testlocation;

        public LocationTests()
        {
            // TODO uncomment below to create an instance of Location
            //instance = new Location();
            testlocation = new Location();
            //testlocation.Id = 1;


        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Location
        /// </summary>
        [Fact]
        public void LocationInstanceTest()
        {
            // TODO uncomment below to test "IsType" Location
            //Assert.IsType<Location>(instance);
            Assert.IsType<Location>(testlocation);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
            testlocation.Id = 1;
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
            testlocation.Name = "testname";
        }

    }

}
