name: api-integration-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check if docker-compose is available.
      run: docker-compose --version
    - name: Build images
      run: docker-compose -f docker-compose.integration-test.yml build
    - name: Run services and tests
      run: docker-compose -f docker-compose.integration-test.yml up --exit-code-from api-test
    - name: Run docker containers for JMeter
      run: docker-compose --network=host -f docker-compose.integration-test.yml up -d
    - name: Run netstat
      run: netstat -atup
    - name: Run JMeter Tests
      uses: rbhadti94/apache-jmeter-action@v0.3.1
      with:
        testFilePath: api/test/testPlan.jmx
        outputReportsFolder: api/reports/
    - name: Archive jmeter results
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-report
        path: api/reports/*
    - name: Shut down docker containers
      run: docker-compose down