name: api-integration-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check if docker-compose is available.
      run: docker-compose --version
