name: .NET

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      working-directory: RapidGuestRegistration/
      run: dotnet restore
    - name: Build
      working-directory: RapidGuestRegistration/
      run: dotnet build --no-restore
    - name: Test
      working-directory: RapidGuestRegistration/
      run: dotnet test --no-build --verbosity normal
